title: Hello, world! I'm Nathaniel Yu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nathaniel Yu # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a web developer focusing on back-end development. Always hungry to keep learning. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: iyuke # add your Github handle
linkedin: # add your Linkedin handle
email: 1209862616@qq.com

# Disqus
discus-identifier: mr-right # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
